export const UPDATE_PORTFOLIO_ITEMS = 'UPDATE_PORTFOLIO_ITEMS';
export const UPDATE_CURRENT_STATUS = 'UPDATE_CURRENT_STATUS';
export const SEND_MAIL_REQUEST = 'SEND_MAIL_REQUEST';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILED = 'SEND_MAIL_FAILED';
